import type { TarotCard, Suit } from './types';

export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: '0',
    name: 'The Fool',
    suit: 'major',
    number: 0,
    description: "A carefree traveler steps toward the cliff's edge, white rose in hand, dog at heel — innocence setting out before the journey has rules.",
    meaningUpright: 'New beginnings, optimism, trust in life',
    meaningReversed: 'Recklessness, folly, risk-taking',
  },
  {
    id: '1',
    name: 'The Magician',
    suit: 'major',
    number: 1,
    description: 'One hand raised to heaven, one pointed to earth, all four suit emblems on his table — will made into a channel.',
    meaningUpright: 'Action, power, manifestation, inspired action',
    meaningReversed: 'Manipulation, poor planning, unfulfilled potential',
  },
  {
    id: '2',
    name: 'The High Priestess',
    suit: 'major',
    number: 2,
    description: 'Enthroned between the black and white pillars, scroll half-hidden, the moon at her feet — keeper of what is not said.',
    meaningUpright: 'Intuition, knowledge, subconscious, inner voice',
    meaningReversed: 'Secrets, disconnected from intuition, withdrawal',
  },
  {
    id: '3',
    name: 'The Empress',
    suit: 'major',
    number: 3,
    description: 'Crowned with stars in a ripening field, her shield marked with Venus — creation in full bloom.',
    meaningUpright: 'Femininity, nature, abundance, nurturing',
    meaningReversed: 'New ideas, creative block, smothering',
  },
  {
    id: '4',
    name: 'The Emperor',
    suit: 'major',
    number: 4,
    description: 'Grey-bearded on a ram-headed stone throne, orb and sceptre in hand — order held in place by will.',
    meaningUpright: 'Authority, structure, foundation, father figure',
    meaningReversed: 'Dominance, excessive control, lack of structure',
  },
  {
    id: '5',
    name: 'The Hierophant',
    suit: 'major',
    number: 5,
    description: 'A robed teacher blesses two acolytes between twin pillars, crossed keys at his feet — tradition handing down its keys.',
    meaningUpright: 'Tradition, institution, spiritual wisdom',
    meaningReversed: 'Change, rebellion, personal beliefs',
  },
  {
    id: '6',
    name: 'The Lovers',
    suit: 'major',
    number: 6,
    description: 'An angel blesses a man and woman beneath a heavy sun, the tree and the serpent behind them — a choice sealed at the level of values.',
    meaningUpright: 'Love, harmony, relationships, values alignment',
    meaningReversed: 'Self-love, disharmony, imbalance, choices',
  },
  {
    id: '7',
    name: 'The Chariot',
    suit: 'major',
    number: 7,
    description: 'An armored victor stands in a chariot drawn by one black and one white sphinx, no reins in sight — motion mastered by will alone.',
    meaningUpright: 'Control, willpower, victory, determination',
    meaningReversed: 'Lack of control, aggression, loss of direction',
  },
  {
    id: '8',
    name: 'Strength',
    suit: 'major',
    number: 8,
    description: "A garlanded woman gently closes a lion's jaws, an infinity sign above her brow — power tamed by patience.",
    meaningUpright: 'Courage, persuasion, influence, compassion',
    meaningReversed: 'Self-doubt, weakness, raw emotion',
  },
  {
    id: '9',
    name: 'The Hermit',
    suit: 'major',
    number: 9,
    description: 'A cloaked elder on the mountaintop lifts a lantern holding a six-pointed star — light carried inward and shared sparingly.',
    meaningUpright: 'Soul-searching, introspection, solitude, guidance',
    meaningReversed: 'Isolation, loneliness, withdrawal',
  },
  {
    id: '10',
    name: 'Wheel of Fortune',
    suit: 'major',
    number: 10,
    description: 'A great wheel ringed with letters and creatures turns in the open sky, a sphinx perched on top — the turning that no one steers.',
    meaningUpright: 'Good luck, karma, life cycles, turning point',
    meaningReversed: 'Bad luck, resistance to change, breaking cycles',
  },
  {
    id: '11',
    name: 'Justice',
    suit: 'major',
    number: 11,
    description: 'Crowned and seated, sword upright in one hand and scales level in the other — consequence weighed to the grain.',
    meaningUpright: 'Justice, fairness, truth, law',
    meaningReversed: 'Injustice, dishonesty, lack of accountability',
  },
  {
    id: '12',
    name: 'The Hanged Man',
    suit: 'major',
    number: 12,
    description: 'A man hangs by one foot from a living tree, face serene, head haloed — the world seen right by being turned upside down.',
    meaningUpright: 'Pause, surrender, new perspective, letting go',
    meaningReversed: 'Delay, resistance, letting go of control',
  },
  {
    id: '13',
    name: 'Death',
    suit: 'major',
    number: 13,
    description: 'A skeleton in black armor rides a pale horse past king and child alike, a white rose on its banner — the ending that clears the field.',
    meaningUpright: 'Endings, change, transformation, transition',
    meaningReversed: 'Resistance to change, avoidance, late endings',
  },
  {
    id: '14',
    name: 'Temperance',
    suit: 'major',
    number: 14,
    description: 'A winged figure pours water between two cups, one foot on land and one in the stream — the art of the middle way.',
    meaningUpright: 'Balance, moderation, patience, purpose',
    meaningReversed: 'Imbalance, excess, lack of direction',
  },
  {
    id: '15',
    name: 'The Devil',
    suit: 'major',
    number: 15,
    description: 'A horned figure crouches above two chained captives — whose chains hang loose enough to lift off. Bondage kept by belief.',
    meaningUpright: 'Shadow self, attachment, addiction, restriction',
    meaningReversed: 'Release, liberation, detachment',
  },
  {
    id: '16',
    name: 'The Tower',
    suit: 'major',
    number: 16,
    description: 'Lightning splits a crowned tower and figures fall through the dark — the false structure coming down at a single stroke.',
    meaningUpright: 'Sudden change, upheaval, chaos, revelation',
    meaningReversed: 'Delayed change, fear of change, avoidance',
  },
  {
    id: '17',
    name: 'The Star',
    suit: 'major',
    number: 17,
    description: 'Under one great star a kneeling figure pours water onto land and pool alike — hope after the storm, naked and undefended.',
    meaningUpright: 'Hope, faith, purpose, renewal',
    meaningReversed: 'Lack of faith, disconnection, despair',
  },
  {
    id: '18',
    name: 'The Moon',
    suit: 'major',
    number: 18,
    description: 'A dog and a wolf howl at a clouded moon between two towers while a crayfish climbs from the pool — the path walked in half-light.',
    meaningUpright: 'Illusion, fear, anxiety, intuition',
    meaningReversed: 'Release of fear, confusion, subconscious',
  },
  {
    id: '19',
    name: 'The Sun',
    suit: 'major',
    number: 19,
    description: 'A laughing child rides a white horse beneath a full-faced sun and a wall of sunflowers — daylight with nothing to hide.',
    meaningUpright: 'Optimism, joy, success, vitality',
    meaningReversed: 'Temporary sadness, pessimism, lack of clarity',
  },
  {
    id: '20',
    name: 'Judgement',
    suit: 'major',
    number: 20,
    description: "An angel's trumpet wakes the dead from their coffins, arms raised to answer — the call that cannot be unheard.",
    meaningUpright: 'Judgement, rebirth, calling, awakening',
    meaningReversed: 'Self-doubt, inner critic, refusal of calling',
  },
  {
    id: '21',
    name: 'The World',
    suit: 'major',
    number: 21,
    description: 'A dancer wrapped in a laurel wreath, the four living creatures at the corners — the circle closed, the journey whole.',
    meaningUpright: 'Completion, accomplishment, travel, fulfillment',
    meaningReversed: 'Unfinished business, lack of closure, delays',
  },
];

const RANK_NAMES = ['Ace', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Page', 'Knight', 'Queen', 'King'];

type MinorSuit = Exclude<Suit, 'major'>;

const SUIT_TITLE: Record<MinorSuit, string> = {
  wands: 'Wands',
  cups: 'Cups',
  swords: 'Swords',
  pentacles: 'Pentacles',
};

// [meaningUpright, meaningReversed, description] per rank, Ace → King.
const SUIT_TEXTS: Record<MinorSuit, [string, string, string][]> = {
  wands: [
    ['Inspiration, new opportunity, creative spark', 'Delays, lack of direction, false starts', 'A hand from a cloud offers a living, sprouting wand — pure creative fire before it has taken form.'],
    ['Planning, future vision, a decision taking shape', 'Fear of change, playing it safe, staying put', 'A figure holds a small globe and looks out from castle walls between two planted wands.'],
    ['Expansion, foresight, progress underway', 'Obstacles to plans, delays, shortsightedness', 'A merchant watches his ships from a clifftop, three wands rooted beside him.'],
    ['Celebration, homecoming, a milestone reached', 'Instability at home, transition, shaky foundations', 'A flower garland strung between four wands before a castle in festival.'],
    ['Friction, competition, scattered efforts', 'Avoiding conflict, tension finally released', 'Five youths clash wands in a mock battle where no one is truly hurt.'],
    ['Victory, recognition, public success', 'Fall from favor, ego, delayed reward', 'A laureled rider parades on horseback through an admiring crowd.'],
    ['Standing your ground, defending a position', 'Overwhelm, giving ground, burnout', 'A defender on high ground holds off six wands thrust up from below.'],
    ['Swift movement, news arriving, momentum', 'Delays, frustration, energy scattered mid-flight', 'Eight wands fly together through open sky toward their landing.'],
    ['Resilience, persistence, the last stand', 'Paranoia, exhaustion, defenses built too high', 'A bandaged fighter leans on his wand, guarding the eight planted behind him.'],
    ['Burden, overextension, carrying too much alone', 'Release, delegation, the load finally set down', 'A figure hauls ten heavy wands toward a distant town, bent double under them.'],
    ['Enthusiasm, exploration, a spark of news', 'Hesitation, scattered enthusiasm, all talk', 'A youth in open desert holds up a wand and studies its sprouting tip.'],
    ['Bold pursuit, passion in motion, adventure', 'Recklessness, impulsiveness, fire without aim', 'An armored rider charges forward on a rearing horse, wand raised like a banner.'],
    ['Confidence, warmth, magnetic determination', 'Jealousy, demands, self-doubt behind the blaze', 'A queen enthroned with sunflower and wand, a black cat alert at her feet.'],
    ['Visionary leadership, boldness matured', 'Tyranny of vision, impatience with slower souls', 'A king leans forward on his throne, salamanders biting their tails on his robe.'],
  ],
  cups: [
    ['New love, emotional opening, compassion', 'Blocked feelings, emptiness, love withheld', 'A chalice overflows in five streams while a dove descends into it — the heart before it chooses.'],
    ['Partnership, mutual attraction, union', 'Imbalance, a broken bond, miscommunication', 'Two figures exchange cups beneath a winged lion — feeling given and returned in equal measure.'],
    ['Celebration, friendship, community', 'Gossip, excess, a third wheel', 'Three friends raise their cups in a dance among the harvest.'],
    ['Apathy, contemplation, an offer unseen', 'Renewed motivation, finally accepting help', 'A seated figure ignores three cups before him — and the fourth being offered from a cloud.'],
    ['Loss, grief, dwelling on what spilled', 'Acceptance, turning toward what remains', 'A cloaked mourner stands over three spilled cups, blind to the two still standing behind.'],
    ['Nostalgia, innocence, kindness returned', 'Stuck in the past, rose-tinted memory', 'A child hands a cup of flowers to a smaller child in an old walled garden.'],
    ['Fantasy, many choices, wishful thinking', 'Clarity after illusion, decisive focus', 'Seven visions rise from seven cups in a cloud — castles, jewels, laurels, a shrouded figure.'],
    ['Walking away, seeking deeper meaning', 'Fear of moving on, one more try', 'A figure turns from eight stacked cups and climbs toward the mountains under an eclipsed moon.'],
    ['Contentment, a wish fulfilled, satisfaction', 'Smugness, hollow indulgence, wanting more', 'A satisfied host sits arms-crossed before nine cups arced behind him like trophies.'],
    ['Lasting happiness, family harmony, home', 'Fractured harmony, ideals of home unmet', 'A family rejoices beneath a rainbow of ten cups over their cottage.'],
    ['A message of feeling, curiosity, imagination', 'Emotional immaturity, moody signals', 'A youth in a flowered tunic studies a fish peeking back from his cup.'],
    ['A romantic offer, following the heart', 'Moody pursuit, promises outrunning truth', 'A knight rides slowly forward, cup extended like an invitation.'],
    ['Empathy, deep intuition, emotional steadiness', 'Emotional flooding, martyrdom, care turned inward', 'A queen contemplates an ornate covered cup at the edge of the sea.'],
    ['Emotional mastery, calm counsel', 'Repression, manipulation through feeling', 'A king sits enthroned on a restless sea, his cup perfectly steady.'],
  ],
  swords: [
    ['Clarity, breakthrough, truth cutting through', 'Confusion, a truth used as a weapon', 'A crowned blade rises from a cloud — the mind at its sharpest and coldest.'],
    ['Stalemate, a decision refused', 'The blindfold slips, a choice forced', 'A blindfolded woman balances two crossed swords before a moonlit sea.'],
    ['Heartbreak, painful truth, grief', 'Healing after sorrow, forgiveness begun', 'A heart pierced by three swords under storm and rain.'],
    ['Rest, recovery, deliberate truce', 'Restlessness, burnout ignored', 'A knight lies in effigy in a quiet chapel, one sword beneath him, three above.'],
    ['A hollow victory, conflict at any cost', 'Reconciliation, cutting your losses', 'A smirking victor gathers swords while the defeated walk away.'],
    ['Transition, passage to calmer water', 'Resisting the crossing, baggage aboard', 'A ferryman poles a mother and child across still water, six swords standing in the boat.'],
    ['Strategy, stealth, acting alone', 'Confession, coming clean, a scheme half-done', 'A figure tiptoes from a camp carrying five of seven swords, glancing back.'],
    ['Feeling trapped, self-imposed limits', 'Stepping free, seeing the way out', 'A bound and blindfolded figure stands ringed by eight swords — the ring is open.'],
    ['Anxiety, sleepless dread, the mind at 3 a.m.', 'Dawn after the worst night, asking for help', 'A figure sits bolt upright in bed, face in hands, nine swords mounted on the dark wall.'],
    ['A painful ending, rock bottom', 'Recovery begins, the worst has passed', 'Ten swords pin a fallen figure to the shore — and beyond them, dawn is breaking.'],
    ['Curiosity, watchfulness, new ideas', 'Gossip, scattered mental energy', 'An alert youth holds a sword upright against a gusting wind, eyes everywhere.'],
    ['Swift, decisive action', 'Haste, cutting words, charging blind', 'A knight gallops full-tilt into the wind, sword leveled.'],
    ['Clear-eyed independence, honest counsel', 'Coldness, bitterness from old wounds', 'A stern queen extends one hand while her sword stands perfectly upright.'],
    ['Intellectual authority, impartial truth', 'Abuse of reason, cold verdicts', 'A king faces straight ahead, sword tilted slightly — judgment ready to fall either way.'],
  ],
  pentacles: [
    ['Opportunity, seed money, a tangible start', 'A missed chance, shaky ground for a venture', 'A hand from a cloud offers a golden coin above a garden gate — potential you can hold.'],
    ['Juggling, adaptability, balance in motion', 'Dropped balls, overcommitment', 'A dancer juggles two coins bound in an infinity loop while ships heave on the sea behind.'],
    ['Teamwork, craft recognized, apprenticeship', 'Working at cross purposes, shoddy work', 'A mason confers with monk and architect beneath his carving in the cathedral.'],
    ['Security held tight, saving, control', 'Hoarding, fear of loss — or the grip loosening', 'A crowned figure clutches one coin to his chest, stands on two, balances one on his head.'],
    ['Hardship, feeling shut out in the cold', 'Recovery, help accepted, the door was open', 'Two ragged figures pass a lit church window in the snow.'],
    ['Generosity, fair exchange, help that balances', 'Strings attached, one-sided charity', 'A merchant weighs alms in a scale, giving to one beggar while another waits.'],
    ['Patience, assessment, the long view', 'Impatience, doubting sunk costs', 'A farmer leans on his hoe, studying the vine of coins he has grown so far.'],
    ['Diligence, skill-building, craftsmanship', 'Perfectionism, joyless repetition', 'An apprentice engraves pentacle after pentacle, each hung neatly beside the last.'],
    ['Self-sufficiency, earned luxury, discipline paid off', 'Overwork behind the garden walls, dependence', 'A gowned figure with a hooded falcon walks her abundant vineyard alone.'],
    ['Legacy, family wealth, lasting foundations', 'A squandered inheritance, friction over money', 'An elder with his dogs watches family pass under an archway hung with ten coins.'],
    ['Study, a practical opportunity, diligence begun', 'Procrastination, plans that stay daydreams', 'A youth holds a single coin up to the light, absorbed in it.'],
    ['Methodical progress, reliability', 'Stagnation, plodding without vision', 'A knight sits a motionless workhorse in a plowed field, coin held out before him.'],
    ['Practical nurture, resourceful comfort', 'Smothering care, work and home out of balance', 'A queen cradles a coin in her lap inside a bower of blossom and small creatures.'],
    ['Prosperity, steady mastery, patronage', 'Greed, clinging to status, stubborn materialism', 'A robed king sits among vines on a bull-carved throne, one hand on his coin.'],
  ],
};

export const MINOR_ARCANA: TarotCard[] = (Object.keys(SUIT_TEXTS) as MinorSuit[]).flatMap((suit) =>
  SUIT_TEXTS[suit].map(([meaningUpright, meaningReversed, description], i) => ({
    id: `${suit}-${i + 1}`,
    name: `${RANK_NAMES[i]} of ${SUIT_TITLE[suit]}`,
    suit,
    number: i + 1,
    description,
    meaningUpright,
    meaningReversed,
  })),
);

export const FULL_DECK: TarotCard[] = [...MAJOR_ARCANA, ...MINOR_ARCANA];
