"""
Distill the attacker: search-over-sim teacher -> tiny student -> weights.json

All-JS project: the SHIPPED model is weights.json read by a ~15-line JS forward pass
(see index.html). This script is the OFFLINE trainer. The ML stays in Python (numpy);
only the *data* comes from the sim.

  >>> SEAM <<<  Right now data is generated by the BOOTSTRAP sim below — a reduced,
  Python copy of the rules so the pipeline runs today. Once sim.ts exists, delete the
  bootstrap and point `load_dataset()` at a JSON of (observation, leak_vector) pairs
  exported by a headless Node run of sim.ts. Nothing else changes.
"""
import numpy as np, json, os
rng = np.random.default_rng(7)
OUT = os.path.dirname(os.path.abspath(__file__))

# ===================================================================================
# BOOTSTRAP SIM  (temporary — replace with sim.ts export; see SEAM note above)
# 7-element wheel: Sonic>Earth>Zap>Ice>Fire>Sonic ; Light<->Dark mutual. 1.5 / 0.5 / 1.0
# ===================================================================================
ELEMS  = ["Fire","Ice","Earth","Sonic","Zap","Light","Dark"]
TRAITS = ["Grunt","Swarm","Flier","Shade"]
IN_LABELS = [f"dps_{e}" for e in ELEMS] + ["anti_air","detection","splash"]
N_ACT = len(ELEMS)*len(TRAITS)  # 28
BEATS = {3:2, 2:4, 4:1, 1:0, 0:3}
def type_mult(P,E):
    if BEATS.get(P)==E: return 1.5
    if BEATS.get(E)==P: return 0.5
    if (P,E) in ((5,6),(6,5)): return 1.5
    return 1.0
CHART = np.array([[type_mult(P,E) for E in range(7)] for P in range(7)])
B, T = 100.0, 1.0

def sample_defense():
    k = rng.integers(1,4)
    idx = rng.choice(7, size=k, replace=False)
    dps = np.zeros(7); w = rng.uniform(0.3,1.0,size=k); w/=w.sum()
    dps[idx] = rng.uniform(30,150)*w
    return np.concatenate([dps, rng.uniform(0,1,3)]).astype(np.float32)

def leak_vector(obs):
    dps, aa, det, splash = obs[:7], obs[7], obs[8], obs[9]
    out = np.empty(N_ACT, np.float32)
    for E in range(7):
        base = float((dps*CHART[:,E]).sum())
        for ti,tr in enumerate(TRAITS):
            eff = base
            if   tr=="Flier": eff *= aa
            elif tr=="Shade": eff *= det
            elif tr=="Swarm": eff *= (0.4+0.6*splash)
            out[E*len(TRAITS)+ti] = max(0.0, B - eff*T)
    return out

def load_dataset(n):
    """SEAM: swap this body for `json.load(open('dataset.json'))` from sim.ts."""
    X = np.stack([sample_defense() for _ in range(n)])
    Y = np.stack([leak_vector(x) for x in X])   # teacher = exhaustive search over 28 actions
    return X, Y

# ===================================================================================
# ML — search-teacher distill (stays in Python regardless of where the sim lives)
# ===================================================================================
Xtr,Ytr = load_dataset(20000); Xte,Yte = load_dataset(4000)
mu, sd = Xtr.mean(0), Xtr.std(0)+1e-6
yscale = Ytr.max()
Xtr_n, Ytr_s = (Xtr-mu)/sd, Ytr/yscale
Xte_n = (Xte-mu)/sd

H = 64
def he(a,b): return (rng.standard_normal((a,b))*np.sqrt(2/a)).astype(np.float32)
P = {"W1":he(10,H),"b1":np.zeros(H,np.float32),"W2":he(H,N_ACT),"b2":np.zeros(N_ACT,np.float32)}
m = {k:np.zeros_like(v) for k,v in P.items()}; v = {k:np.zeros_like(v) for k,v in P.items()}
def fwd(X): z1=X@P["W1"]+P["b1"]; a1=np.maximum(z1,0); return z1,a1,a1@P["W2"]+P["b2"]

lr,B1,B2,eps = 2e-3,0.9,0.999,1e-8; n=Xtr_n.shape[0]; t=0
for epoch in range(60):
    for s in range(0,n,256):
        bi = rng.permutation(n)[s:s+256]; x=Xtr_n[bi]; y=Ytr_s[bi]
        z1,a1,pred = fwd(x); d=(pred-y)*(2/len(bi))
        g={"W2":a1.T@d,"b2":d.sum(0)}
        da1=d@P["W2"].T; da1[z1<=0]=0
        g["W1"]=x.T@da1; g["b1"]=da1.sum(0); t+=1
        for k in P:
            m[k]=B1*m[k]+(1-B1)*g[k]; v[k]=B2*v[k]+(1-B2)*g[k]**2
            P[k]-=lr*(m[k]/(1-B1**t))/(np.sqrt(v[k]/(1-B2**t))+eps)

_,_,pred = fwd(Xte_n); stu=pred.argmax(1); ora=Yte.argmax(1)
row=np.arange(len(Xte)); regret=(Yte[row,ora]-Yte[row,stu]).mean()
print(f"top-1 vs search: {(stu==ora).mean()*100:.1f}%   leak regret: {regret/Yte[row,ora].mean()*100:.1f}%")

# ---- fold input-standardization into layer 1; export weights.json ------------------
# raw x feeds the JS forward pass directly (no preprocessing needed in the browser).
W1 = (P["W1"]/sd[:,None]).astype(float)
b1 = (P["b1"] - (P["W1"]*(mu/sd)[:,None]).sum(0)).astype(float)
W2 = P["W2"].astype(float); b2 = P["b2"].astype(float)   # output = monotonic leak proxy (argmax is what the game uses)
json.dump({
  "arch":"mlp-relu", "in":10, "hidden":H, "out":N_ACT,
  "in_labels":IN_LABELS, "elems":ELEMS, "traits":TRAITS,
  "W1":W1.tolist(), "b1":b1.tolist(), "W2":W2.tolist(), "b2":b2.tolist(),
}, open(f"{OUT}/weights.json","w"))
print("wrote weights.json (%d params, %d bytes)" % (
    W1.size+b1.size+W2.size+b2.size, os.path.getsize(f"{OUT}/weights.json")))
